config/routes.rb
Rails.application.routes.draw do
  default_url_options host: Rails.env.production? ? 'example.com' : 'localhost:3000'

  resources :occurrences do
    member do
      patch :upvote
      patch :downvote
    end

    resources :comments
  end

  post 'reports/:class/:class_id' => 'reports#create', as: :reports

  devise_for :admins
  devise_for :users

  root 'map#map'

end

app/models/occurrence.rb
class Occurrence < ActiveRecord::Base
  # Validations
  # validates :time,        presence: true
  validates :description, presence: true
  validates :location,    presence: true
  # validates :latitude,    presence: true
  # validates :longitude,   presence: true

  # Virtual attributes used in the form
  attr_accessor :hour
  attr_accessor :date

  # Callbacks
  before_save :set_defaults, on: :create

  # Relations
  belongs_to :user
  has_many   :comments
  has_many   :reports

  def as_json(options={})
    options[:except] ||= [:updated_at, :user_id] # Retira esses attrs do JSON
    super(options)
  end

  def upvote
    Rails.logger.info "Rating: #{rating.nil? ? 'nil' : rating}"
    increment(:rating)
    Rails.logger.info "Rating: #{rating}"
  end

  def downvote
    decrement!(:rating)
  end

  def set_latitute_and_longitude
    geo = Geocoder.search(location).first
    self.latitude = geo.latitude
    self.longitude = geo.longitude
  end

  def get_lat_long(location)
    geo = Geocoder.search(location).first
    self.latitude  = geo.latitude
    self.longitude = geo.longitude
  end

  def set_time
    hour    = @hour.split(':')[0].to_i
    minutes = @hour.split(':')[1].to_i

    year  = @date.split('/')[2].to_i
    month = @date.split('/')[1].to_i
    day   = @date.split('/')[0].to_i

    self.time = DateTime.new(year, month, day, hour, minutes, 0, '-3')
  end

private
  # Callback functions
  def set_defaults
    self.rating = 0
  end
  # End of Callback functions
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController
  before_action :set_occurrence, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  layout 'empty', only: [:show]

  # CRUD #################################################################################################

  # GET /occurrences
  # GET /occurrences.json
  def index
    @occurrences = Occurrence.all
    respond_to do |format|
      format.html
      format.json { render json: @occurrences }
    end
  end

  # GET /occurrences/1
  # GET /occurrences/1.json
  def show
    @comment = Comment.new
    @comments = @occurrence.comments.order('created_at DESC')
  end

  # GET /occurrences/new
  def new
    @occurrence = Occurrence.new
  end

  # GET /occurrences/1/edit
  def edit
  end

  # POST /occurrences
  # POST /occurrences.json
  def create
    @occurrence = current_user.occurrences.build(occurrence_params)
    set_lat_lgn
    set_time

    respond_to do |format|
      if @occurrence.save
        format.html { redirect_to root_path, notice: 'Occurrence was successfully created.' }
        format.json { render :show, status: :created, location: @occurrence }
      else
        format.html { render :new }
        format.json { render json: @occurrence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occurrences/1
  # PATCH/PUT /occurrences/1.json
  def update
    respond_to do |format|
      if @occurrence.update(occurrence_params)
        format.html { redirect_to @occurrence, notice: 'Occurrence was successfully updated.' }
        format.json { render :show, status: :ok, location: @occurrence }
      else
        format.html { render :edit }
        format.json { render json: @occurrence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occurrences/1
  # DELETE /occurrences/1.json
  def destroy
    @occurrence.destroy
    respond_to do |format|
      format.html { redirect_to occurrences_url, notice: 'Occurrence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # End of CRUD #################################################################################################

  def upvote
    @occurrence.upvote()

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: @resource }
      format.js   { render nothing: true }
    end
  end

  def downvote
    @occurrence.downvote()

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: @resource }
      format.js   { render nothing: true }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_occurrence
    @occurrence = Occurrence.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def occurrence_params
    params.require(:occurrence).permit(:description, :date, :hour, :rating, :latitude, :longitude, :location)
  end

  def set_lat_lgn
    @occurrence.get_lat_long(occurrence_params[:location])
  end

  def set_time
    @occurrence.set_time
  end
end

app/helpers/occurrences_helper.rb
module OccurrencesHelper
end

app/views/occurrences/_form.html.erb
<%= form_for(@occurrence) do |f| %>
  <% if @occurrence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@occurrence.errors.count, "error") %> prohibited this occurrence from being saved:</h2>

      <ul>
      <% @occurrence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :date %>
  <%= f.text_field :date, class: 'date', placeholder: 'dd/mm/aaaa' %>

  <%= f.label :hour %>
  <%= f.text_field :hour, class: 'hour', placeholder: 'hh:mm', onkeyup: 'validateHour()' %>
  <div id="occurrence_hour_error" class="red-text">Digite um horário válido!</div>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit 'Submeter', class: 'modal-action modal-close btn red', id: 'submit_button' %>
<% end %>

app/views/occurrences/_modal_new.html.erb
<% if current_user.present? %>
  <div id="new_occurrence_modal" class="modal">
    <div class="modal-content center-align">
      <%= form_for(@occurrence) do |f| %>
        <% if @occurrence.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@occurrence.errors.count, "error") %> prohibited this occurrence from being saved:</h2>

            <ul>
            <% @occurrence.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">
          <div class="col s6">
            <%= f.label :date %><div id="occurrence_date_error" class="red-text">(Digite uma data válida!)</div>
            <%= f.text_field :date, class: 'date', placeholder: 'dd/mm/aaaa', onkeyup: 'validateDate()' %>
          </div>

          <div class="col s6">
            <%= f.label :hour %><div id="occurrence_hour_error" class="red-text">(Digite um horário válido!)</div>
            <%= f.text_field :hour, class: 'hour', placeholder: 'hh:mm', onkeyup: 'validateHour()' %>
          </div>

          <div class="col s12">
            <%= f.label :location %>
            <%= f.text_field :location %>
          </div>

          <div class="col s12 input-field">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'materialize-textarea' %>
          </div>

          <div class="col s12">
            <%= f.submit 'Submeter', class: 'modal-action modal-close btn red', id: 'submit_button' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/occurrences/_modal_show.html.erb
<div id="show_occurrence_modal" class="modal">
  <div class="modal-content center-align">
    <div class="show-occurrence">
      <!-- jQuery vai adicionar HTML aqui -->
    </div>
  </div>
</div>

app/views/occurrences/edit.html.erb
<h1>Editing Occurrence</h1>

<%= render 'form' %>

<%= link_to 'Show', @occurrence %> |
<%= link_to 'Back', occurrences_path %>

app/views/occurrences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Occurrences</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Time</th>
      <th>Rating</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @occurrences.each do |occurrence| %>
      <tr>
        <td><%= occurrence.description %></td>
        <td><%= occurrence.time %></td>
        <td><%= occurrence.rating %></td>
        <td><%= occurrence.latitude %></td>
        <td><%= occurrence.longitude %></td>
        <td><%= occurrence.location %></td>
        <td><%= link_to 'Show', occurrence %></td>
        <td><%= link_to 'Edit', edit_occurrence_path(occurrence) %></td>
        <td><%= link_to 'Destroy', occurrence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Occurrence', new_occurrence_path %>

app/views/occurrences/new.html.erb
<h1>New Occurrence</h1>

<%= render 'form' %>

<%= link_to 'Back', occurrences_path %>

app/views/occurrences/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s8 left">
    <p>
      <b>Local</b><br>
      <%= @occurrence.location %>
    </p>
  </div>

  <div class="col s4 right">
    <p>
      <%= @occurrence.time.strftime('%d/%m/%Y às %H:%m') %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col s6 left">
    <b>Popularidade:</b>
    <span class="rating">
      <%= @occurrence.rating %>
    </span>
    <div class="voting">
      <%= link_to upvote_occurrence_path(@occurrence.id), remote: true, method: :patch do %>
        <i class="material-icons green-text">thumb_up</i>
      <% end %>

      <%= link_to downvote_occurrence_path(@occurrence.id), method: :patch, remote: true do %>
        <i class="material-icons red-text">thumb_down</i>
      <% end %>
    </div>
  </div>

  <div class="col s6">
    <%= link_to 'Reportar Ocorrencia', reports_path(@occurrence.class.to_s, @occurrence.id), method: :post, class: "btn btn-primary" %>
  </div>
</div>

<div class="row">
  <div class="col s12 m8">
    <b>Descrição:</b>
    <p>
      <%= @occurrence.description %>
    </p>
  </div>

</div>

<div class="new_occurrence_comment">
  <div class="row">
    <div class="col s12">
      <h6>Deixe o seu comentário:</h6>
    </div>
    <%= render 'comments/form' %>
  </div>
</div>

<div id="occurrence_comments">
  <h5 class="center-align">Comentários</h5>
  <ul class="collection">
    <% @comments.each do |comment| %>
      <li class="collection-item">
        <div class="row">
          <div class="col s6 left">
            <b><%= comment.user.first_name %></b>
          </div>

          <div class="col s6 right">
            <span class="right grey-text"><%= comment.created_at.strftime('%H:%m %d/%m/%Y') %></span>
            <span class="right">
              <%= link_to 'Reportar comentário', reports_path(comment.class.to_s, comment.id), method: :post, class: "btn small" %>
            </span>
          </div>

          <div class="col s12">
            <%= comment.body %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
  votingButtons = $('div.voting a');
  buttonsIcons = $('div.voting a i');
  rating = $('span.rating');

  votingButtons.click(function() {
    buttonsIcons.removeClass('red-text green-text');
    buttonsIcons.addClass('grey-text');
    rating.text(parseInt(rating.text().trim()) + 1)
    votingButtons.fadeOut(500);
  });
</script>